Add SSO Application CRUD capabilities
descope/python-sdk pull request #328
Opened 2024-01-17 07:19 UTC by guyp-descope

2024-01-17 21:30 UTC, dorsha approved these changes
Nice!
Make sure to add e2e tests to it.

2024-01-17 21:33 UTC, shilgapira requested changes
My updates for the proto and environment upgrade are almost ready

2024-01-18 11:04 UTC, shilgapira submitted a review, later dismissed

2024-01-21 16:03 UTC, dorsha approved these changes

2024-01-21 16:13 UTC, merged